const ADD_NEW_RECIPE = "ADD_NEW_RECIPE";
const GET_RECIPE = "GET_RECIPE";
const GET_DETAIL = "GET_DETAIL";
const GET_DIETS = "GET_DIETS";
const FILTER_DIET = "FILTER_DIET";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const SORT_RECIPES = "SORT_RECIPES";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const RESET_DETAIL = "RESET_DETAIL";
const SET_LOADING = "SET_LOADING";

module.exports = {
    ADD_NEW_RECIPE,
    GET_RECIPE,
    GET_DETAIL,
    GET_DIETS,
    FILTER_DIET,
    SEARCH_BY_NAME,
    SORT_RECIPES,
    SET_CURRENT_PAGE,
    RESET_DETAIL,
    SET_LOADING
}